### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by EXTER7** [Arcaratus/BloodArsenal#27]
After updating BloodArsenal to 1.2-0 the game crashes on startup

[Crash Report](http://pastebin.com/5WvneiUt)

Seems to be cuased by a wrong import in [ModItems.java](https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/items/ModItems.java#L21) (the import should be 'java.util.Arrays' instead of 'scala.actors.threadpool.Arrays').

**Comment by TehNut** [comment]
@Arcaratus Wrong Arrays class, broseph.

**Comment by Dream-Master** [comment]
Have some similar error:
``````````````````````````````
Caused by: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at com.arc.bloodarsenal.common.items.ModItems.registerThaumcraftItems(ModItems.java:183)
	at com.arc.bloodarsenal.common.BloodArsenal.postInit(BloodArsenal.java:169)
`````````````````
Full Error:
https://gist.github.com/Dream-Master/3ce68fdaa3c90d17fc01#file-gistfile1-txt

**Comment by Dream-Master** [comment]
https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/items/ModItems.java#L183

https://github.com/Arcaratus/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/BloodArsenal.java#L166

**Comment by Arcaratus** [comment]
I'm on it

**Comment by Dream-Master** [comment]
Cool thanks works now :+1:
